site_name: User Manual

nav:
    - Inicio: index.md
    - Home: home.md
    - Display: display.md
    - Dashboard: dashboard.md
    - Reportes: reportes.md
    - Configuracion: configuracion.md
    - Sistema: sistema.md
    - Usuario: usuario.md
    - Selector: selector.md

theme: readthedocs